# Generated by Django 4.2 on 2024-05-02 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название продукта')),
                ('model', models.CharField(max_length=250, verbose_name='модель продукта')),
                ('product_release_date', models.DateField(default=datetime.date.today, verbose_name='дата выхода продукта на рынок')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ['product_release_date'],
            },
        ),
    ]
