# Generated by Django 4.2 on 2024-05-04 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-product_release_date'], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.CreateModel(
            name='NetworkMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название объекта сети')),
                ('email', models.EmailField(max_length=254, verbose_name='почта объекта сети')),
                ('country', models.CharField(max_length=150, verbose_name='страна объекта сети')),
                ('city', models.CharField(max_length=150, verbose_name='город объекта сети')),
                ('street', models.CharField(max_length=150, verbose_name='улица объекта сети')),
                ('house_number', models.CharField(max_length=50, verbose_name='номер дома объекта сети')),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='задолженность перед поставщиком')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания объекта сети')),
                ('products', models.ManyToManyField(to='network.product', verbose_name='продукты объекта сети')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.networkmember', verbose_name='поставщик объекта сети')),
            ],
            options={
                'verbose_name': 'объект сети',
                'verbose_name_plural': 'объекты сети',
                'ordering': ['-created_at'],
            },
        ),
    ]
